import { AddonCategory, PurchaseType } from '@/app/generated/prisma/client'
import { MIN_PLAN_FOR_FEATURE } from './plan-gate'
import { ADDON_FEATURE_MAP } from './addon-features'
import type { Plan } from '@/app/generated/prisma/client'

export type AddonSeed = {
  slug: string
  name: string
  description: string
  longDescription: string
  category: AddonCategory
  icon: string
  price: number
  purchaseType: PurchaseType
  isFeatured: boolean
  configSchema?: Record<string, unknown>
  setupGuide: string
}

function cfg(props: Record<string, unknown>) {
  return JSON.stringify({ type: 'object', properties: props })
}

export const ADDON_SEED_CATALOG: AddonSeed[] = [
  // ─── Kanallar (Sosyal) ───────────────────────────────────────────
  {
    slug: 'whatsapp-channel',
    name: 'WhatsApp Kanalı',
    description: 'WhatsApp Business API ile müşterilerinizle WhatsApp üzerinden iletişim kurun.',
    longDescription: 'Gelen WhatsApp mesajları tek gelen kutusunda toplanır. Chatbot, AI yanıt ve canlı temsilci desteği dahildir.',
    category: AddonCategory.SOCIAL,
    icon: '💬',
    price: 14900,
    purchaseType: PurchaseType.MONTHLY,
    isFeatured: true,
    configSchema: { phoneNumberId: { type: 'string', title: 'Telefon Numarası ID' }, accessToken: { type: 'string', title: 'API Token' }, verifyToken: { type: 'string', title: 'Webhook Doğrulama Token' } },
    setupGuide: '1. Meta Developer Console\'da WhatsApp uygulaması oluşturun\n2. Kanallar sayfasından yapılandırın\n3. Webhook: /api/webhooks/whatsapp',
  },
  {
    slug: 'telegram-channel',
    name: 'Telegram Bot',
    description: 'Telegram botu ile müşterileriniz size Telegram üzerinden ulaşsın.',
    longDescription: 'Telegram Bot API entegrasyonu. Gelen mesajlar gelen kutusuna düşer, temsilci yanıtları Telegram\'a iletilir.',
    category: AddonCategory.SOCIAL,
    icon: '✈️',
    price: 4900,
    purchaseType: PurchaseType.MONTHLY,
    isFeatured: false,
    configSchema: { botToken: { type: 'string', title: 'Bot Token' }, botUsername: { type: 'string', title: 'Bot Kullanıcı Adı' } },
    setupGuide: '1. BotFather ile bot oluşturun\n2. Token\'ı Kanallar sayfasına girin\n3. GET /api/webhooks/telegram?websiteId=SITENIZ ile webhook URL alın',
  },
  {
    slug: 'messenger-channel',
    name: 'Facebook Messenger',
    description: 'Facebook Messenger entegrasyonu ile sayfa mesajlarını yönetin.',
    longDescription: 'Messenger mesajları tek panelde. Meta webhook ile otomatik senkronizasyon ve chatbot desteği.',
    category: AddonCategory.SOCIAL,
    icon: '💭',
    price: 9900,
    purchaseType: PurchaseType.MONTHLY,
    isFeatured: true,
    configSchema: { pageId: { type: 'string', title: 'Sayfa ID' }, pageAccessToken: { type: 'string', title: 'Sayfa Token' }, verifyToken: { type: 'string', title: 'Webhook Token' } },
    setupGuide: '1. Facebook Developer uygulaması oluşturun\n2. Webhook URL: /api/webhooks/meta\n3. Kanallar sayfasından sayfa token girin',
  },
  {
    slug: 'instagram-channel',
    name: 'Instagram Mesajlaşma',
    description: 'Instagram DM entegrasyonu ile Instagram mesajlarınızı yönetin.',
    longDescription: 'Instagram Business DM\'leri gelen kutusunda. Meta Graph API webhook desteği.',
    category: AddonCategory.SOCIAL,
    icon: '📸',
    price: 12900,
    purchaseType: PurchaseType.MONTHLY,
    isFeatured: false,
    configSchema: { businessAccountId: { type: 'string', title: 'İşletme Hesabı ID' }, accessToken: { type: 'string', title: 'Erişim Token' }, verifyToken: { type: 'string', title: 'Webhook Token' } },
    setupGuide: '1. Instagram Business hesabını Facebook\'a bağlayın\n2. Webhook: /api/webhooks/meta\n3. Kanallar sayfasından token girin',
  },
  {
    slug: 'email-channel',
    name: 'E-posta Kanalı',
    description: 'SMTP e-posta kanalı ile müşteri e-postalarını gelen kutusuna alın.',
    longDescription: 'E-posta kanalı yapılandırması ve kampanya gönderimi. SMTP ayarları ile entegre çalışır.',
    category: AddonCategory.SOCIAL,
    icon: '✉️',
    price: 6900,
    purchaseType: PurchaseType.MONTHLY,
    isFeatured: false,
    configSchema: { smtpHost: { type: 'string', title: 'SMTP Sunucusu' }, smtpPort: { type: 'number', title: 'Port' }, smtpUser: { type: 'string', title: 'Kullanıcı' }, smtpPass: { type: 'string', title: 'Şifre' } },
    setupGuide: '1. SMTP bilgilerinizi girin\n2. Kanallar > E-posta bölümünden etkinleştirin',
  },
  // ─── AI ──────────────────────────────────────────────────────────
  {
    slug: 'ai-sohbet-asistani',
    name: 'AI Sohbet Asistanı',
    description: 'GPT/Gemini ile insan gibi konuşan 7/24 AI destek — otomatik yanıt + chatbot akışları.',
    longDescription:
      'Gerçek LLM destekli sohbet asistanı: bilgi bankası bağlamı, doğal dil anlama, temsilciye devir. Chatbot oluşturucu dahil. Profesyonel pakette ücretsiz; alt paketlerde aylık eklenti.',
    category: AddonCategory.AI,
    icon: '🤖',
    price: 34900,
    purchaseType: PurchaseType.MONTHLY,
    isFeatured: true,
    configSchema: {
      provider: { type: 'string', enum: ['openai', 'anthropic', 'gemini', 'groq'], title: 'AI Sağlayıcı' },
      model: { type: 'string', title: 'Model' },
      autoReply: { type: 'boolean', title: 'Oto-Yanıt' },
    },
    setupGuide:
      '1. Ayarlar > AI Sohbet Asistanı sayfasını açın\n2. GPT, Gemini veya Groq seçin\n3. Oto-yanıtı etkinleştirin — müşteriler insan gibi yanıt alır',
  },
  {
    slug: 'ai-agent-pro',
    name: 'AI Asistan Pro',
    description: 'Gelişmiş yapay zeka asistanı — AI Sohbet Asistanı ile aynı özellik seti.',
    longDescription: 'AI öneri, otomatik yanıt, chatbot akışları ve akıllı yönlendirme. GPT/Gemini/Claude desteği.',
    category: AddonCategory.AI,
    icon: '✨',
    price: 29900,
    purchaseType: PurchaseType.MONTHLY,
    isFeatured: false,
    configSchema: { provider: { type: 'string', enum: ['openai', 'anthropic'], title: 'AI Sağlayıcı' }, model: { type: 'string', title: 'Model' }, autoReply: { type: 'boolean', title: 'Oto-Yanıt' } },
    setupGuide: '1. AI Ayarları sayfasından sağlayıcı seçin\n2. API anahtarını girin\n3. Oto-yanıtı etkinleştirin',
  },
  {
    slug: 'ai-copilot',
    name: 'AI Copilot',
    description: 'Temsilci gelen kutusunda bağlama duyarlı yanıt önerileri.',
    longDescription: 'Gelen kutusunda tek tıkla AI yanıt önerisi. Konuşma geçmişine göre kişiselleştirilmiş öneriler.',
    category: AddonCategory.AI,
    icon: '✨',
    price: 19900,
    purchaseType: PurchaseType.MONTHLY,
    isFeatured: true,
    configSchema: { autoSuggest: { type: 'boolean', title: 'Otomatik Öneri', default: true } },
    setupGuide: '1. AI Ayarları > Copilot\'u açın\n2. Gelen kutusunda öneri butonunu kullanın',
  },
  {
    slug: 'ai-chatbot',
    name: 'Chatbot Oluşturucu',
    description: 'Kodsuz chatbot akışları — Başlangıç paketinde eklenti olarak satın alınabilir.',
    longDescription:
      'Görsel chatbot editörü, tetikleyiciler, bilgi bankası entegrasyonu ve canlı temsilciye devir. Tam AI Sohbet için AI Sohbet Asistanı eklentisini tercih edin.',
    category: AddonCategory.AI,
    icon: '🧠',
    price: 14900,
    purchaseType: PurchaseType.MONTHLY,
    isFeatured: true,
    setupGuide: '1. Chatbot ayarlarından bot oluşturun\n2. Tetikleyicileri yapılandırın\n3. Widget\'ta etkinleştirin',
  },
  {
    slug: 'live-translate-pro',
    name: 'Canlı Çeviri Pro',
    description: 'Dünyanın her yerinden müşterilerinizle kendi dilinizde konuşun — çift yönlü otomatik çeviri.',
    longDescription:
      'Ziyaretçi kendi dilini seçer; mesajlar anında çevrilir. Temsilci Türkçe yazar, ziyaretçi Almanca okur — ve tam tersi. Gelen kutusu ve widget\'ta 50+ dil desteği. Başlangıç paketi için bu eklentiyle global sohbet açılır.',
    category: AddonCategory.AI,
    icon: '🌐',
    price: 9900,
    purchaseType: PurchaseType.MONTHLY,
    isFeatured: true,
    setupGuide:
      '1. Eklentiyi satın alın\n2. Widget\'ta ziyaretçi dil seçicisini açın\n3. Gelen kutusunda otomatik çeviri varsayılan olarak açıktır',
  },
  {
    slug: 'sentiment-analysis',
    name: 'Duygu Analizi',
    description: 'Ziyaretçi mesajlarında otomatik duygu tespiti ve uyarılar.',
    longDescription: 'Olumsuz mesajlar gelen kutusunda işaretlenir. Kural tabanlı hızlı analiz.',
    category: AddonCategory.AI,
    icon: '😊',
    price: 3900,
    purchaseType: PurchaseType.MONTHLY,
    isFeatured: false,
    setupGuide: '1. Eklentiyi etkinleştirin\n2. Gelen kutusunda duygu etiketlerini görün',
  },
  // ─── Pazarlama & Etkileşim ───────────────────────────────────────
  {
    slug: 'proactive-chat',
    name: 'Proaktif Sohbet',
    description: 'Sayfa süresi, scroll ve çıkış niyeti ile hedefli mesajlar.',
    longDescription: 'Ziyaretçilere doğru zamanda proaktif mesaj gönderin. EXIT_INTENT, TIME_ON_PAGE tetikleyicileri.',
    category: AddonCategory.MARKETING,
    icon: '🎯',
    price: 5900,
    purchaseType: PurchaseType.MONTHLY,
    isFeatured: true,
    setupGuide: '1. Proaktif Mesajlar sayfasından kural oluşturun\n2. Hedef sayfaları belirleyin',
  },
  {
    slug: 'email-campaigns',
    name: 'E-posta Kampanyaları',
    description: 'Toplu e-posta gönderimi ve pazarlama otomasyonu.',
    longDescription: 'E-posta kampanyaları oluşturun, hedef kitle seçin ve gönderin.',
    category: AddonCategory.MARKETING,
    icon: '📧',
    price: 9900,
    purchaseType: PurchaseType.MONTHLY,
    isFeatured: true,
    setupGuide: '1. Kampanyalar sayfasından e-posta kampanyası oluşturun\n2. Hedef kitleyi seçin\n3. Gönder',
  },
  {
    slug: 'visitor-tracking',
    name: 'Ziyaretçi Takibi',
    description: 'Canlı ziyaretçi listesi, sayfa geçmişi ve davranış takibi.',
    longDescription: 'Kim sitede, hangi sayfada — gerçek zamanlı ziyaretçi paneli.',
    category: AddonCategory.MARKETING,
    icon: '👁️',
    price: 4900,
    purchaseType: PurchaseType.MONTHLY,
    isFeatured: false,
    setupGuide: '1. Widget\'ı sitenize ekleyin\n2. Dashboard > Ziyaretçiler bölümünü açın',
  },
  // ─── Destek ──────────────────────────────────────────────────────
  {
    slug: 'knowledge-base',
    name: 'Bilgi Bankası',
    description: 'Yardım merkezi makaleleri ve widget içi self-servis destek.',
    longDescription: 'Kategoriler, makaleler ve widget bilgi bankası entegrasyonu.',
    category: AddonCategory.SUPPORT,
    icon: '📚',
    price: 4900,
    purchaseType: PurchaseType.MONTHLY,
    isFeatured: false,
    setupGuide: '1. Bilgi Bankası > Kategori oluşturun\n2. Makale ekleyin\n3. Widget\'ta gösterin',
  },
  {
    slug: 'ticketing-system',
    name: 'Bilet Sistemi',
    description: 'Destek talepleri, durum takibi ve temsilci ataması.',
    longDescription: 'Sohbetten bilet oluşturma, durum yönetimi ve mesaj geçmişi.',
    category: AddonCategory.SUPPORT,
    icon: '🎫',
    price: 4900,
    purchaseType: PurchaseType.MONTHLY,
    isFeatured: false,
    setupGuide: '1. Biletler sayfasından talep oluşturun\n2. Temsilci atayın',
  },
  {
    slug: 'csat-ratings',
    name: 'CSAT Puanlama',
    description: 'Sohbet sonrası müşteri memnuniyeti anketi.',
    longDescription: '1-5 yıldız puanlama ve geri bildirim toplama.',
    category: AddonCategory.SUPPORT,
    icon: '⭐',
    price: 2900,
    purchaseType: PurchaseType.MONTHLY,
    isFeatured: false,
    setupGuide: '1. Puanlama ayarlarını yapılandırın\n2. Widget otomatik anket gösterir',
  },
  {
    slug: 'canned-responses',
    name: 'Hazır Cevaplar',
    description: 'Tek tıkla hızlı yanıt şablonları.',
    longDescription: 'Sık kullanılan yanıtları kaydedin ve gelen kutusunda kullanın.',
    category: AddonCategory.SUPPORT,
    icon: '💬',
    price: 1900,
    purchaseType: PurchaseType.MONTHLY,
    isFeatured: false,
    setupGuide: '1. Hazır Cevaplar sayfasından şablon ekleyin\n2. Gelen kutusunda /komut ile kullanın',
  },
  // ─── Otomasyon & Entegrasyon ─────────────────────────────────────
  {
    slug: 'workflow-automation',
    name: 'Workflow Otomasyonu',
    description: 'Olay tetiklemeli otomasyon kuralları.',
    longDescription: 'Mesaj alındığında, sohbet açıldığında otomatik aksiyonlar.',
    category: AddonCategory.AUTOMATION,
    icon: '⚡',
    price: 7900,
    purchaseType: PurchaseType.MONTHLY,
    isFeatured: false,
    setupGuide: '1. Otomasyon sayfasından workflow oluşturun\n2. Tetikleyici ve aksiyon seçin',
  },
  {
    slug: 'webhooks-api',
    name: 'Webhook & Zapier',
    description: 'Olay bildirimleri için webhook uç noktaları.',
    longDescription: 'Yeni sohbet, mesaj ve bilet olaylarını harici sistemlere iletin. Zapier/Make uyumlu.',
    category: AddonCategory.AUTOMATION,
    icon: '🔗',
    price: 4900,
    purchaseType: PurchaseType.MONTHLY,
    isFeatured: false,
    setupGuide: '1. Webhook ayarlarından URL ekleyin\n2. Olay türlerini seçin',
  },
  {
    slug: 'rest-api',
    name: 'REST API Erişimi',
    description: 'Programatik API erişimi ve entegrasyon.',
    longDescription: 'Sohbet, ziyaretçi ve bilet verilerine API ile erişin.',
    category: AddonCategory.AUTOMATION,
    icon: '🔌',
    price: 5900,
    purchaseType: PurchaseType.MONTHLY,
    isFeatured: false,
    setupGuide: '1. API anahtarınızı ayarlardan alın\n2. Dokümantasyona göre entegre edin',
  },
  {
    slug: 'slack-integration',
    name: 'Slack Entegrasyonu',
    description: 'Slack kanalına yeni sohbet bildirimleri.',
    longDescription: 'Slack bot token ile kanal bildirimleri. Kanallar sayfasından yapılandırın.',
    category: AddonCategory.AUTOMATION,
    icon: '🔔',
    price: 3900,
    purchaseType: PurchaseType.MONTHLY,
    isFeatured: false,
    configSchema: { botToken: { type: 'string', title: 'Bot Token' }, channel: { type: 'string', title: 'Kanal ID' } },
    setupGuide: '1. Slack uygulaması oluşturun\n2. Kanallar > Slack bölümünden token girin',
  },
  {
    slug: 'status-page',
    name: 'Durum Sayfası',
    description: 'Herkese açık sistem durumu ve olay sayfası.',
    longDescription: 'Bileşen durumları, olay geçmişi ve abonelik bildirimleri.',
    category: AddonCategory.SUPPORT,
    icon: '📡',
    price: 4900,
    purchaseType: PurchaseType.MONTHLY,
    isFeatured: false,
    setupGuide: '1. Durum Sayfası ayarlarından bileşen ekleyin\n2. Alt alan adınızı yapılandırın',
  },
  // ─── Analitik & CRM ──────────────────────────────────────────────
  {
    slug: 'advanced-analytics',
    name: 'Gelişmiş Analitik',
    description: 'Detaylı raporlar, CSV export ve performans metrikleri.',
    longDescription: 'Konuşma analitiği, ekip performansı ve veri dışa aktarma.',
    category: AddonCategory.ANALYTICS,
    icon: '📊',
    price: 7900,
    purchaseType: PurchaseType.MONTHLY,
    isFeatured: true,
    setupGuide: '1. Dashboard analitik bölümünü açın\n2. Raporları CSV olarak indirin',
  },
  {
    slug: 'crm-advanced',
    name: 'Gelişmiş CRM',
    description: 'Ziyaretçi profilleri, etiketler ve iletişim geçmişi.',
    longDescription: 'Kişi kartları, notlar ve çok kanallı geçmiş birleştirme.',
    category: AddonCategory.CRM,
    icon: '👥',
    price: 5900,
    purchaseType: PurchaseType.MONTHLY,
    isFeatured: false,
    setupGuide: '1. Kişiler sayfasından ziyaretçi profillerini görüntüleyin\n2. Not ve etiket ekleyin',
  },
  {
    slug: 'ecommerce-tracker',
    name: 'E-ticaret Takibi',
    description: 'Sayfa görüntüleme, sepet ve dönüşüm takibi.',
    longDescription: 'Widget oturum takibi ile ziyaretçi yolculuğu ve sayfa analitiği.',
    category: AddonCategory.ECOMMERCE,
    icon: '🛒',
    price: 9900,
    purchaseType: PurchaseType.MONTHLY,
    isFeatured: false,
    configSchema: { platform: { type: 'string', enum: ['woocommerce', 'shopify', 'custom'], title: 'Platform' }, storeUrl: { type: 'string', title: 'Mağaza URL' } },
    setupGuide: '1. Widget snippet\'ini e-ticaret sitenize ekleyin\n2. Ziyaretçi geçmişinden takip edin',
  },
  // ─── Özel ────────────────────────────────────────────────────────
  {
    slug: 'screen-co-browsing',
    name: 'Ekran İzleme & Co-browsing',
    description: 'Canlı ekran görüntüsü ve ziyaretçi oturumu izleme.',
    longDescription: 'Gerçek zamanlı ekran paylaşımı ile müşteriye canlı yardım.',
    category: AddonCategory.CUSTOM,
    icon: '🖥️',
    price: 14900,
    purchaseType: PurchaseType.MONTHLY,
    isFeatured: true,
    setupGuide: '1. Gelen kutusunda ziyaretçi seçin\n2. Ekran izlemeyi başlatın',
  },
  {
    slug: 'white-label',
    name: 'Beyaz Etiket (White-label)',
    description: 'Tüm marka izlerini kaldırın, kendi markanızı kullanın.',
    longDescription: 'Widget ve panelde özel logo, renk ve alan adı.',
    category: AddonCategory.CUSTOM,
    icon: '🏷️',
    price: 19900,
    purchaseType: PurchaseType.MONTHLY,
    isFeatured: true,
    configSchema: { companyName: { type: 'string', title: 'Şirket Adı' }, logoUrl: { type: 'string', title: 'Logo URL' }, customDomain: { type: 'string', title: 'Özel Domain' } },
    setupGuide: '1. Widget marka ayarlarını yapılandırın\n2. Logonuzu yükleyin',
  },
]

export function getAddonMeta(slug: string) {
  const feature = ADDON_FEATURE_MAP[slug]
  const requiredPlan = feature ? (MIN_PLAN_FOR_FEATURE[feature] as Plan | undefined) : undefined
  return { feature: feature || null, requiredPlan: requiredPlan || null }
}
