export const PLAN_LIMITS = {
  FREE: {
    maxAgents: 2,
    maxConversationsPerMonth: 100,
    chatbot: false,
    visitorTracking: false,
    cannedResponses: false,
    webhooks: false,
    apiAccess: false,
    customBranding: false,
    fileUpload: false,
    overlayAI: false,
    aiAssistant: false,
    knowledgeBase: false,
    ticketing: false,
    campaigns: false,
    multiChannel: false,
    workflows: false,
    statusPage: false,
    autoTranslate: false,
  },
  STARTER: {
    maxAgents: 5,
    maxConversationsPerMonth: 1000,
    chatbot: true,
    visitorTracking: true,
    cannedResponses: true,
    webhooks: false,
    apiAccess: false,
    customBranding: false,
    fileUpload: true,
    overlayAI: false,
    aiAssistant: false,
    knowledgeBase: true,
    ticketing: true,
    campaigns: false,
    multiChannel: false,
    workflows: false,
    statusPage: false,
    autoTranslate: false,
  },
  PRO: {
    maxAgents: 25,
    maxConversationsPerMonth: Infinity,
    chatbot: true,
    visitorTracking: true,
    cannedResponses: true,
    webhooks: true,
    apiAccess: true,
    customBranding: false,
    fileUpload: true,
    overlayAI: true,
    aiAssistant: true,
    knowledgeBase: true,
    ticketing: true,
    campaigns: true,
    multiChannel: true,
    workflows: true,
    statusPage: true,
    autoTranslate: true,
  },
  BUSINESS: {
    maxAgents: Infinity,
    maxConversationsPerMonth: Infinity,
    chatbot: true,
    visitorTracking: true,
    cannedResponses: true,
    webhooks: true,
    apiAccess: true,
    customBranding: true,
    fileUpload: true,
    overlayAI: true,
    aiAssistant: true,
    knowledgeBase: true,
    ticketing: true,
    campaigns: true,
    multiChannel: true,
    workflows: true,
    statusPage: true,
    autoTranslate: true,
  },
} as const

export type PlanType = keyof typeof PLAN_LIMITS

export const DEFAULT_WIDGET_SETTINGS = {
  primaryColor: '#1972F5',
  position: 'BOTTOM_RIGHT' as const,
  welcomeMessage: 'Merhaba! Size nasıl yardıncı olabiliriz?',
  offlineMessage: 'Şu an çevrimdışısınız. Bir mesaj bırakın, size dönelim.',
}

export const PLANS = [
  {
    id: 'FREE',
    name: 'Ücretsiz',
    price: 0,
    popular: false,
    description: 'Küçük işletmeler için temel canlı destek',
    features: [
      '2 temsilci',
      '100 sohbet/ay',
      'Temel widget',
      'E-posta bildirimleri',
      'Temel istatistikler',
    ],
    highlighted: false,
  },
  {
    id: 'STARTER',
    name: 'Başlangıç',
    price: 1790,
    popular: false,
    description: 'Büyüyen işletmeler için gelişmiş özellikler',
    features: [
      '5 temsilci',
      '1.000 sohbet/ay',
      'Ziyaretçi takibi',
      'Chatbot & Otomasyon',
      'Bilgi Bankası',
      'Bilet Sistemi',
      'Hazır cevaplar',
      'Dosya yükleme',
    ],
    highlighted: false,
  },
  {
    id: 'PRO',
    name: 'Profesyonel',
    price: 3790,
    popular: true,
    description: 'Profesyonel ekipler için tam donanım',
    features: [
      '25 temsilci',
      'Sınırsız sohbet',
      'Ekran İzleme (Canlı müdahale)',
      'AI destekli akıllı yardım',
      '50+ Dil Otomatik Çeviri',
      'Bilgi Bankası & Bilet Sistemi',
      'E-posta Kampanyaları',
      'Çoklu Kanal (WhatsApp/Email/Messenger/Instagram)',
      'Otomasyon Workflow\'ları',
      'Durum Sayfası',
      'API & Webhook',
      'Gelişmiş Analitik & Raporlar',
      'Öncelikli destek',
    ],
    highlighted: true,
  },
  {
    id: 'BUSINESS',
    name: 'Kurumsal',
    price: 11990,
    popular: false,
    description: 'Kurumsal çözümler için sınırsız paket',
    features: [
      'Sınırsız temsilci',
      'Sınırsız sohbet',
      'Ekran İzleme (Canlı müdahale)',
      'AI destekli akıllı yardım',
      '50+ Dil Otomatik Çeviri',
      'Tüm özellikler',
      'Özel marka (White-label)',
      'SLA garantisi (%99.9)',
      'Özel destek hattı (7/24)',
      'Özel entegrasyon',
      'Özel API limitleri',
      'Öncelikli güncelleme',
    ],
    highlighted: false,
  },
] as const