export const PLAN_LIMITS = {
  FREE: {
    maxAgents: 2,
    maxConversationsPerMonth: 300,
    chatbot: false,
    visitorTracking: false,
    cannedResponses: false,
    webhooks: false,
    apiAccess: false,
    customBranding: false,
    fileUpload: false,
    overlayAI: false,
    aiAssistant: false,
    knowledgeBase: false,
    ticketing: false,
    campaigns: false,
    multiChannel: false,
    workflows: false,
    statusPage: false,
    autoTranslate: false,
    ratings: false,
    proactiveMessages: false,
    advancedAnalytics: false,
    aiRag: false,
  },
  STARTER: {
    maxAgents: 5,
    maxConversationsPerMonth: 1000,
    chatbot: false,
    visitorTracking: true,
    cannedResponses: true,
    webhooks: false,
    apiAccess: false,
    customBranding: false,
    fileUpload: true,
    overlayAI: false,
    aiAssistant: false,
    knowledgeBase: true,
    ticketing: true,
    campaigns: false,
    multiChannel: false,
    workflows: false,
    statusPage: false,
    autoTranslate: false,
    ratings: true,
    proactiveMessages: true,
    advancedAnalytics: false,
    aiRag: false,
  },
  PRO: {
    maxAgents: 25,
    maxConversationsPerMonth: Infinity,
    chatbot: true,
    visitorTracking: true,
    cannedResponses: true,
    webhooks: true,
    apiAccess: true,
    customBranding: false,
    fileUpload: true,
    overlayAI: true,
    aiAssistant: true,
    knowledgeBase: true,
    ticketing: true,
    campaigns: true,
    multiChannel: true,
    workflows: true,
    statusPage: true,
    autoTranslate: true,
    ratings: true,
    proactiveMessages: true,
    advancedAnalytics: true,
    aiRag: true,
  },
  BUSINESS: {
    maxAgents: Infinity,
    maxConversationsPerMonth: Infinity,
    chatbot: true,
    visitorTracking: true,
    cannedResponses: true,
    webhooks: true,
    apiAccess: true,
    customBranding: true,
    fileUpload: true,
    overlayAI: true,
    aiAssistant: true,
    knowledgeBase: true,
    ticketing: true,
    campaigns: true,
    multiChannel: true,
    workflows: true,
    statusPage: true,
    autoTranslate: true,
    ratings: true,
    proactiveMessages: true,
    advancedAnalytics: true,
    aiRag: true,
  },
} as const

export type PlanType = keyof typeof PLAN_LIMITS

export const DEFAULT_WIDGET_SETTINGS = {
  primaryColor: '#9333EA',
  position: 'BOTTOM_RIGHT' as const,
  welcomeMessage: 'Merhaba! Size nasıl yardıncı olabiliriz?',
  offlineMessage: 'Şu an çevrimdışısınız. Bir mesaj bırakın, size dönelim.',
}

export const PLANS = [
  {
    id: 'FREE',
    name: 'Ücretsiz',
    price: 0,
    popular: false,
    description: 'Küçük işletmeler için temel canlı destek',
    features: [
      '2 temsilci',
      '300 sohbet/ay',
      'Temel widget',
      'E-posta bildirimleri',
      'Temel istatistikler',
    ],
    highlighted: false,
  },
  {
    id: 'STARTER',
    name: 'Başlangıç',
    price: 490,
    popular: false,
    description: 'Büyüyen işletmeler için gelişmiş özellikler',
    features: [
      '5 temsilci',
      '1.000 sohbet/ay',
      'Ziyaretçi takibi & proaktif mesajlar',
      'Bilgi bankası (makale) & bilet sistemi',
      'Hazır cevaplar & dosya yükleme',
      'Eklenti: AI Sohbet (₺349/ay)',
      'Eklenti: RAG eğitimi (₺199/ay)',
      'Eklenti: WhatsApp / SMS / LinkedIn',
    ],
    highlighted: false,
  },
  {
    id: 'PRO',
    name: 'Profesyonel',
    price: 990,
    popular: true,
    description: 'Profesyonel ekipler için tam donanım',
    features: [
      '25 temsilci',
      'Sınırsız sohbet',
      'AI Sohbet + RAG + Copilot + Sesli AI',
      'Chatbot, web araması & çoklu modal görsel AI',
      'WhatsApp, SMS, LinkedIn & tüm kanallar',
      '50+ dil otomatik çeviri',
      'Ekran izleme & akıllı temsilci yönlendirme',
      'AI analitik, duygu analizi & devir özeti',
      'Kampanya, otomasyon, API & gelişmiş raporlar',
    ],
    highlighted: true,
  },
  {
    id: 'BUSINESS',
    name: 'Kurumsal',
    price: 2490,
    popular: false,
    description: 'Kurumsal çözümler için sınırsız paket',
    features: [
      'Sınırsız temsilci & sohbet',
      'Profesyonel paketteki tüm AI & kanallar',
      'Premium AI modelleri (GPT-4o, Claude Opus)',
      'Özel marka (White-label)',
      'SLA garantisi (%99.9)',
      '7/24 öncelikli destek & özel entegrasyon',
      'Özel API limitleri & öncelikli güncelleme',
    ],
    highlighted: false,
  },
] as const