export const PLAN_LIMITS = {
  FREE: {
    maxAgents: 2,
    maxConversationsPerMonth: 100,
    chatbot: false,
    visitorTracking: false,
    cannedResponses: false,
    webhooks: false,
    apiAccess: false,
    customBranding: false,
    fileUpload: false,
    overlayAI: false,
    aiAssistant: false,
  },
  STARTER: {
    maxAgents: 5,
    maxConversationsPerMonth: 1000,
    chatbot: true,
    visitorTracking: true,
    cannedResponses: true,
    webhooks: false,
    apiAccess: false,
    customBranding: false,
    fileUpload: true,
    overlayAI: false,
    aiAssistant: false,
  },
  PRO: {
    maxAgents: 15,
    maxConversationsPerMonth: Infinity,
    chatbot: true,
    visitorTracking: true,
    cannedResponses: true,
    webhooks: true,
    apiAccess: true,
    customBranding: false,
    fileUpload: true,
    overlayAI: true,
    aiAssistant: true,
  },
  BUSINESS: {
    maxAgents: Infinity,
    maxConversationsPerMonth: Infinity,
    chatbot: true,
    visitorTracking: true,
    cannedResponses: true,
    webhooks: true,
    apiAccess: true,
    customBranding: true,
    fileUpload: true,
    overlayAI: true,
    aiAssistant: true,
  },
} as const

export type PlanType = keyof typeof PLAN_LIMITS

export const DEFAULT_WIDGET_SETTINGS = {
  primaryColor: '#6C3CE1',
  position: 'BOTTOM_RIGHT' as const,
  welcomeMessage: 'Merhaba! Size nasıl yardıncı olabiliriz?',
  offlineMessage: 'Şu an çevrimdışısınız. Bir mesaj bırakın, size dönelim.',
}

export const PLANS = [
  {
    id: 'FREE',
    name: 'Ücretsiz',
    price: 0,
    description: 'Küçük işletmeler için temel canlı destek',
    features: [
      '2 temsilci',
      '100 sohbet/ay',
      'Temel widget',
      'E-posta bildirimleri',
    ],
  },
  {
    id: 'STARTER',
    name: 'Başlangıç',
    price: 199,
    description: 'Büyüyen işletmeler için gelişmiş özellikler',
    features: [
      '5 temsilci',
      '1.000 sohbet/ay',
      'Ziyaretçi takibi',
      'Chatbot',
      'Hazır cevaplar',
      'Dosya yükleme',
    ],
  },
  {
    id: 'PRO',
    name: 'Profesyonel',
    price: 499,
    description: 'Profesyonel ekipler için tam donanım',
    features: [
      '15 temsilci',
      'Sınırsız sohbet',
      'Ekran İzleme (Canlı ekran izleme)',
      'AI destekli canlı yardım',
      'API erişimi',
      'Webhook desteği',
      'Öncelikli destek',
    ],
  },
  {
    id: 'BUSINESS',
    name: 'İş',
    price: 999,
    description: 'Kurumsal çözümler için sınırsız paket',
    features: [
      'Sınırsız temsilci',
      'Sınırsız sohbet',
      'Ekran İzleme (Canlı ekran izleme)',
      'AI destekli canlı yardım',
      'Özel marka',
      'SLA garantisi',
      'Özel destek',
      'Tüm özellikler',
    ],
  },
] as const